src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $resume = null;

    #[ORM\Column(length: 255)]
    private ?string $editeur = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateEdition = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\ManyToOne(inversedBy: 'livres')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorie $categorie = null;

    /**
     * @var Collection<int, LigneCommande>
     */
    #[ORM\OneToMany(targetEntity: LigneCommande::class, mappedBy: 'livre')]
    private Collection $ligneCommandes;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $isbn = null;

    #[ORM\Column]
    private ?int $qte_en_stock = null;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(?string $resume): static
    {
        $this->resume = $resume;

        return $this;
    }

    public function getEditeur(): ?string
    {
        return $this->editeur;
    }

    public function setEditeur(string $editeur): static
    {
        $this->editeur = $editeur;

        return $this;
    }

    public function getDateEdition(): ?\DateTimeInterface
    {
        return $this->dateEdition;
    }

    public function setDateEdition(\DateTimeInterface $dateEdition): static
    {
        $this->dateEdition = $dateEdition;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, LigneCommande>
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): static
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes->add($ligneCommande);
            $ligneCommande->setLivre($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): static
    {
        if ($this->ligneCommandes->removeElement($ligneCommande)) {
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getLivre() === $this) {
                $ligneCommande->setLivre(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): static
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getQteEnStock(): ?int
    {
        return $this->qte_en_stock;
    }

    public function setQteEnStock(int $qte_en_stock): static
    {
        $this->qte_en_stock = $qte_en_stock;

        return $this;
    }
}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Livre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('image')
            ->add('resume')
            ->add('editeur')
            ->add('dateEdition', null, [
                'widget' => 'single_text',
            ])
            ->add('prix')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/livre')]
final class LivreController extends AbstractController
{
    #[Route(name: 'app_livre_index', methods: ['GET'])]
    function index(LivreRepository $livreRepository, Request $request, PaginatorInterface $paginator): Response
    {
    $searchTerm = $request->query->get('search');

    $query = $livreRepository->findBySearchQuery($searchTerm);

    $livres = $paginator->paginate(
        $query, /* Résultats à paginer */
        $request->query->getInt('page', 1), /* Numéro de page */
        12 /* Limite par page */
    );

    return $this->render('livre/index.html.twig', [
        'livres' => $livres,
        'searchTerm' => $searchTerm,
    ]);
}

    #[Route('/new', name: 'app_livre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();

            return $this->redirectToRoute('app_livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_livre_show', methods: ['GET'])]
    public function show(Livre $livre): Response
    {
        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_livre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_livre_delete', methods: ['POST'])]
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_livre_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/admin/LivreController.php
<?php

namespace App\Controller\admin;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/livre')]
final class LivreController extends AbstractController
{
    #[Route(name: 'admin_livre_index', methods: ['GET'])]
    function index(LivreRepository $livreRepository, Request $request, PaginatorInterface $paginator): Response
    {
    $searchTerm = $request->query->get('search');

    $query = $livreRepository->findBySearchQuery($searchTerm);

    $livres = $paginator->paginate(
        $query, /* Résultats à paginer */
        $request->query->getInt('page', 1), /* Numéro de page */
        12 /* Limite par page */
    );

    return $this->render('admin/livre/index.html.twig', [
        'livres' => $livres,
        'searchTerm' => $searchTerm,
    ]);
}

    #[Route('/new', name: 'admin_livre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();

            return $this->redirectToRoute('admin_livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'admin_livre_show', methods: ['GET'])]
    public function show(Livre $livre): Response
    {
        return $this->render('admin/livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    #[Route('/{id}/edit', name: 'admin_livre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('admin_livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'admin_livre_delete', methods: ['POST'])]
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_livre_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/admin/UserController.php
<?php

namespace App\Controller\admin;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;


#[Route('admin/user')]
final class UserController extends AbstractController
{
    #[Route(name: 'admin_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('admin/user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'admin_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager,UserPasswordHasherInterface $passwordHasher): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $plainPassword = $form->get('password')->getData();
            $hashedPassword = $passwordHasher->hashPassword($user, $plainPassword);
            $user->setPassword($hashedPassword);
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('admin_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'admin_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('admin/user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'admin_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('admin_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'admin_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/user/CategorieController.php
<?php

namespace App\Controller\user;

use App\Entity\Categorie;
use App\Form\CategorieType;
use App\Repository\CategorieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('user/categorie')]
final class CategorieController extends AbstractController
{
    #[Route(name: 'user_categorie_index', methods: ['GET'])]
    public function index(CategorieRepository $categorieRepository): Response
    {
        return $this->render('categorie/index.html.twig', [
            'categories' => $categorieRepository->findAll(),
        ]);
    }
}

src/Controller/user/LivreController.php
<?php

namespace App\Controller\user;

use App\Entity\Livre;
use App\Repository\LivreRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/user/livre')]
final class LivreController extends AbstractController
{
    #[Route(name: 'user_livre_index', methods: ['GET'])]
    function index(LivreRepository $livreRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $searchTerm = $request->query->get('search');

        $query = $livreRepository->findBySearchQuery($searchTerm);

        $livres = $paginator->paginate(
            $query, /* Résultats à paginer */
            $request->query->getInt('page', 1), /* Numéro de page */
            12 /* Limite par page */
        );

        return $this->render('user/livre/index.html.twig', [
            'livres' => $livres,
            'searchTerm' => $searchTerm,
        ]);
    }

    #[Route('/{id}', name: 'user_livre_show', methods: ['GET'])]
    public function show(Livre $livre, LivreRepository $livreRepository): Response
    {
        // Récupérer les livres de la même catégorie (similaires) en excluant le livre actuel
        $similarBooks = [];
        if ($livre->getCategorie()) {
            $similarBooks = $livreRepository->createQueryBuilder('l')
                ->where('l.categorie = :categorie')
                ->andWhere('l.id != :currentId')
                ->setParameter('categorie', $livre->getCategorie())
                ->setParameter('currentId', $livre->getId())
                ->orderBy('l.id', 'DESC')
                ->setMaxResults(4)
                ->getQuery()
                ->getResult();
        }

        return $this->render('user/livre/show.html.twig', [
            'livre' => $livre,
            'similarBooks' => $similarBooks,
        ]);
    }

}

templates/user/livre/index.html.twig
{% extends 'user/user_base.html.twig' %}

{% block title %}ReadUp - Catalogue{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .book-card {
            border: none;
            border-radius: 10px;
            overflow: hidden;
            transition: all 0.3s ease;
            height: 100%;
        }

        .book-card:hover {
            transform: translateY(-10px);
            box-shadow: 0 15px 30px rgba(0, 0, 0, 0.1);
        }

        .book-card .card-img-container {
            height: 250px;
            overflow: hidden;
            position: relative;
            background-color: #fff9f5;
        }

        .book-card img {
            height: 100%;
            width: 100%;
            object-fit: contain;
            padding: 20px;
            transition: all 0.5s ease;
        }

        .book-card:hover img {
            transform: scale(1.05);
        }

        .book-card .price-badge {
            position: absolute;
            top: 15px;
            right: 15px;
            background-color: #ffb5a7;
            color: var(--dark);
            border-radius: 50px;
            padding: 8px 15px;
            font-weight: 600;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .book-card .card-body {
            padding: 20px;
        }

        .book-card .card-title {
            font-weight: 600;
            margin-bottom: 10px;
            font-size: 1.1rem;
            color: #2D3436;
        }

        .book-card .card-text {
            color: #95A5A6;
            font-size: 0.9rem;
        }

        .book-card .card-footer {
            background-color: white;
            border-top: 1px solid rgba(0, 0, 0, 0.05);
            padding: 15px 20px;
        }

        .section-title {
            position: relative;
            font-family: 'Nunito', sans-serif;
            font-weight: 700;
            margin-bottom: 30px;
            display: inline-block;
        }

        .section-title::after {
            content: '';
            position: absolute;
            bottom: -10px;
            left: 0;
            width: 80px;
            height: 4px;
            background-color: #8bd3d6;
        }

        @keyframes fadeInUp {
            from {
                opacity: 0;
                transform: translateY(20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        .animate-card {
            animation: fadeInUp 0.5s ease forwards;
            opacity: 0;
        }
        .btn-primary:disabled {
            background-color: #e0e0e0;
            border-color: #d0d0d0;
            color: #999;
            cursor: not-allowed;
            position: relative;
        }

        .btn-primary:disabled:hover {
            background-color: #e0e0e0;
            border-color: #d0d0d0;
        }

        /* Optionnel : Style pour le tooltip en cas de rupture */
        .tooltip-inner {
            max-width: 200px;
            padding: 8px 12px;
            background-color: #fff;
            color: #333;
            border: 1px solid #ddd;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }

        .bs-tooltip-auto[data-popper-placement^=top] .tooltip-arrow::before,
        .bs-tooltip-top .tooltip-arrow::before {
            border-top-color: #ddd;
        }
    </style>
{% endblock %}

{% block body %}
    <!-- Barre de recherche -->
    <div class="search-container">
        <h4 class="search-title">Trouvez votre prochain livre préféré</h4>
        <form method="get" action="{{ path('user_livre_index') }}">
            <div class="input-group">
                <span class="input-group-text bg-white"><i class="bi bi-search"></i></span>
                <input type="text" name="search" class="form-control form-control-lg"
                       placeholder="Rechercher un livre par titre,éditeur..."
                       value="{{ searchTerm ?? '' }}">
                <button type="submit" class="btn btn-primary px-4">
                    <i class="bi bi-search me-2"></i>Rechercher
                </button>
            </div>
        </form>
    </div>

    <!-- En-tête de la section -->
    <h2 class="section-title">
        {% if searchTerm %}
            Résultats de recherche
        {% else %}
            Notre catalogue
        {% endif %}
    </h2>

    <!-- Message de résultats de recherche -->
    {% if searchTerm %}
        <div class="alert alert-info mb-4">
            <i class="bi bi-info-circle me-2"></i>
            Vous avez recherché "<strong>{{ searchTerm }}</strong>"
            ({{ livres.getTotalItemCount }} livre{% if livres.getTotalItemCount > 1 %}s{% endif %} trouvé{% if livres.getTotalItemCount > 1 %}s{% endif %})
        </div>
    {% endif %}

    <!-- Grille de livres -->
    {% if livres|length > 0 %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 mb-4">
            {% for livre in livres %}
                <div class="col animate-card" style="animation-delay: {{ loop.index0 * 0.05 }}s">
                    <div class="book-card shadow-sm">
                        <div class="card-img-container">
                            {% if livre.image %}
                                <img src="{{ livre.image }}" alt="Couverture {{ livre.titre }}">
                            {% else %}
                                <div class="d-flex align-items-center justify-content-center h-100">
                                    <i class="bi bi-book text-secondary" style="font-size: 3rem;"></i>
                                </div>
                            {% endif %}
                            <span class="price-badge">{{ livre.prix|number_format(2, ',', ' ') }} €</span>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ livre.titre }}</h5>
                            <p class="card-text mb-1">{{ livre.editeur }}</p>
                            <p class="card-text"><small class="text-muted">Édité le {{ livre.dateEdition ? livre.dateEdition|date('d/m/Y') : 'date inconnue' }}</small></p>
                        </div>
                        <div class="card-footer">
                            <div class="d-flex justify-content-between">
                                <a href="{{ path('user_livre_show', {'id': livre.id}) }}" class="btn btn-outline-primary btn-sm" data-bs-toggle="tooltip" title="Voir les détails">
                                    <i class="bi bi-eye me-1"></i> Détails
                                </a>
                                <button class="btn btn-primary btn-sm btn-add-to-cart"
                                        data-book-id="{{ livre.id }}"
                                        {{ livre.qteEnStock <= 0 ? 'disabled' : '' }}
                                        data-bs-toggle="tooltip"
                                        title="{{ livre.qteEnStock <= 0 ? 'Produit en rupture de stock' : 'Ajouter au panier' }}">
                                    <i class="bi bi-cart-plus me-1"></i>
                                    {{ livre.qteEnStock <= 0 ? 'Indisponible' : 'Ajouter' }}
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-warning">
            <i class="bi bi-exclamation-triangle me-2"></i> Aucun livre trouvé.
            {% if searchTerm %}
                <a href="{{ path('user_livre_index') }}" class="alert-link ms-2">Afficher tous les livres</a>
            {% endif %}
        </div>
    {% endif %}

    <!-- Pagination -->
    {% if livres|length > 0 %}
        <div class="d-flex justify-content-center mt-4">
            {{ knp_pagination_render(livres) }}
        </div>
    {% endif %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Gestion de l'ajout au panier
            const addToCartButtons = document.querySelectorAll('.btn-add-to-cart');
            addToCartButtons.forEach(button => {
                button.addEventListener('click', function() {
                    if (this.disabled) return;

                    const bookId = this.getAttribute('data-book-id');
                    const icon = this.querySelector('i');

                    // Animation visuelle
                    icon.classList.remove('bi-cart-plus');
                    icon.classList.add('bi-check');

                    // Envoi AJAX
                    fetch(`/panier/ajouter/${bookId}`, {
                        method: 'POST',
                        headers: {
                            'X-Requested-With': 'XMLHttpRequest'
                        }
                    })
                        .then(response => response.json())
                        .then(data => {
                            // Mise à jour du compteur
                            const cartCount = document.querySelector('.cart-count');
                            if (cartCount) {
                                cartCount.textContent = data.count;
                            }

                            // Notification
                            const toast = new bootstrap.Toast(document.getElementById('cartToast'));
                            toast.show();
                        })
                        .finally(() => {
                            setTimeout(() => {
                                icon.classList.remove('bi-check');
                                icon.classList.add('bi-cart-plus');
                            }, 2000);
                        });
                });
            });
        });
    </script>
{% endblock %}